#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/root-check

# update packages
pacman -Syu

$DIR/grub
$DIR/localization
$DIR/network themachine localdomain
$DIR/fonts
$DIR/packages
$DIR/printing

$DIR/user-add dmadera

su dmadera -P -c "$DIR/packages-aur"
