#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $DIR/root-check

echo  "Edit /etc/pacman.conf and uncoment section multilib"
read -n 1 -s -r -p "Press any key to continue"
pacman -Syu

# pacman packages
pacman -S xf86-video-intel xf86-video-amdgpu acpi
pacman -S xorg xorg-xinit xorg-xbacklight
pacman -S i3 i3status i3lock feh
pacman -S sudo ntfs-3g parted pulseaudio
pacman -S gvim git rxvt-unicode rsync
pacman -S youtube-dl simple-scan samba
pacman -S tee tree bash-completion xclip
pacman -S tar unrar unzip p7zip zip
pacman -S chromium inkscape gimp ffmpeg
pacman -S base-devel file python3
pacman -S openssh
